### ISSUE TITLE
Application not starting

### ISSUE THREAD

**Issue by popiejames** [TobiZog/cinnamon-dynamic-wallpaper#1]
After i've completely setup the Extension trough the Cinnamon Extension Manager, nothing is happening

**Comment by TobiZog** [comment]
Can you describe the error more?

- Did you active the extension?
- Did you restart the system?
- Did the wallpaper changes after activation?
- Did the settings window open?
- Did the Image configurator window open?
- Which version of Linux Mint and Cinnamon do you use?

**Comment by popiejames** [comment]
- ive activated the extension
- restarted the system
- wallpaper didn't change after activation
- the Cinnamon Dynamic Wallpaper settings menu opened
- Image Configurator openend
- Mint 21.2 - cinnamon

**Comment by popiejames** [comment]
After Fiddling around, it fixed itself

**Comment by TobiZog** [comment]
If it appears again, contact me again and we will work on a solution.
