### ISSUE TITLE
Not working after update to Mint 21.3

### ISSUE THREAD

**Issue by graynada** [TobiZog/cinnamon-dynamic-wallpaper#11]
After updating to Linux Mint 21.3 with Cinnamon 6.0.4 the dynamic wallpaper is not working.  It initially loads a 'current' background image then throws an error and does not update after.

Errors from Melange are:

`error t=2024-01-16T06:57:56Z [TypeError: Soup.SessionSync is not a constructor]: Failed to evaluate 'init' function on extension: cinnamon-dynamic-wallpaper@TobiZog
error t=2024-01-16T06:57:56Z 
[cinnamon-dynamic-wallpaper@TobiZog]: Extension cinnamon-dynamic-wallpaper@TobiZog: Could not create extension object.
[cinnamon-dynamic-wallpaper@TobiZog]: Error importing extension.js from cinnamon-dynamic-wallpaper@TobiZog
`

Restarting Cinnamon creates the same behaviour.  I have tried uninstalling CDW and reinstalling, no change

**Comment by TobiZog** [comment]
Why do you close the issue? Do you find a solution?

**Comment by graynada** [comment]
Using the version from Github fixes the issue.  The version available through Cinnamon Extensions is broken

**Comment by TobiZog** [comment]
Do you use an official release or the source code in the repository?

The latest official release is version 1.4 and had issues with Cinnamon 6.0. In the repository is version 2.0 Beta with some bugs/not working features right now, but it worked with Cinnamon 5.4 and higher.

**Comment by graynada** [comment]
> Do you use an official release or the source code in the repository?
> 
> The latest official release is version 1.4 and had issues with Cinnamon 6.0. In the repository is version 2.0 Beta with some bugs/not working features right now, but it worked with Cinnamon 5.4 and higher.

I think I am using the official release, ie installed via Extensions in Cinnamon.  All was good until I updated to Mint 21.3 and presumably Cinnamon 6.0.  I have now downloaded the source from this Github and copied the cinnamon-dynamic-wallpaper@TobiZog folder in to my ~/.local/share/cinnamon/extensions, restarted a Cinnamon and all is good.

There is a post on the Mint forums about this, I will update when i get chance

Great extension BTW, thanks for your work on this

**Comment by TobiZog** [comment]
> > Do you use an official release or the source code in the repository?
> > 
> > The latest official release is version 1.4 and had issues with Cinnamon 6.0. In the repository is version 2.0 Beta with some bugs/not working features right now, but it worked with Cinnamon 5.4 and higher.
> 
> I think I am using the official release, ie installed via Extensions in Cinnamon.  All was good until I updated to Mint 21.3 and presumably Cinnamon 6.0.  I have now downloaded the source from this Github and copied the cinnamon-dynamic-wallpaper@TobiZog folder in to my ~/.local/share/cinnamon/extensions, restarted a Cinnamon and all is good.
> 
> There is a post on the Mint forums about this, I will update when i get chance
> 
> Great extension BTW, thanks for your work on this

You're using the new version 2.0. Keep in mind, that some features like the HEIC import are not working at this moment (I work on it).

I look for the post in the forum.

**Comment by graynada** [comment]
> > > Do you use an official release or the source code in the repository?
> > > The latest official release is version 1.4 and had issues with Cinnamon 6.0. In the repository is version 2.0 Beta with some bugs/not working features right now, but it worked with Cinnamon 5.4 and higher.
> > 
> > 
> > I think I am using the official release, ie installed via Extensions in Cinnamon.  All was good until I updated to Mint 21.3 and presumably Cinnamon 6.0.  I have now downloaded the source from this Github and copied the cinnamon-dynamic-wallpaper@TobiZog folder in to my ~/.local/share/cinnamon/extensions, restarted a Cinnamon and all is good.
> > There is a post on the Mint forums about this, I will update when i get chance
> > Great extension BTW, thanks for your work on this
> 
> You're using the new version 2.0. Keep in mind, that some features like the HEIC import are not working at this moment (I work on it).
> 
> I look for the post in the forum.

Thanks, HEIC import is not something I need so no worries
