### ISSUE TITLE
Not able to add themes with .heic files anymore

### ISSUE THREAD

**Issue by ariamis** [TobiZog/cinnamon-dynamic-wallpaper#14]
Hello,

The extension broke .heic support with the new update, don't know what happened. Now there are square icons with forbidden circle inside the icons showing. I can't reach the ones on the bottom because of my tiny screen. Also can you make the extension resizable to 1280 x 800 please? I'm running an older MBP 13" unfortunately, much appreciated. 

Thank you for your great extension!

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/13105219/cf72b6d4-5341-4e25-b397-dc7256bdfe84)

**Comment by TobiZog** [comment]
For a quick fix: You can drag the window to reach the lower end of the window by pressing Alt-Key and move the window around.

But I will also work on a resizable solution

**Comment by TobiZog** [comment]
I've added a small window mode to the extension, coming with version 2.1

**Comment by ariamis** [comment]
Hello,

Thanks for the tips but that doesnt work for me.

Yours best

Den tis 23 jan. 2024 kl 08:51 skrev TobiZog ***@***.***>:

**Comment by ariamis** [comment]
awesome, thank you! =)

Den fre 26 jan. 2024 kl 17:48 skrev TobiZog ***@***.***>:

**Comment by ariamis** [comment]
Sorry i tested again and alt-key worked, thank you so much!

Den tis 23 jan. 2024 kl 08:51 skrev TobiZog ***@***.***>:
