### ISSUE TITLE
Automatic time configuration wrong

### ISSUE THREAD

**Issue by mabawsa** [TobiZog/cinnamon-dynamic-wallpaper#15]
In the extension, the times are setup strangely. It's daylight from 01:38-22:12 and twilight from 22:12-18:46 and a lot of other strange times.
![Screenshot from 2024-02-04 22-44-17](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/7529270/e077349c-91a2-4bf5-b786-ba99fc255ef4)

**Comment by TobiZog** [comment]
Which version of the extension do you use?
Which method do you use to estimate the location (network, custom coordinates, manual times)?

**Comment by Leafback** [comment]
I have the same issue, with very similar but not the same time ranges for each period. 

I use the version downloaded off of Mint's Extensions manager. I don't see a version number anywhere in the app to give more info than this, and I'm also a bit new to Linux to describe better of how I downloaded it.

I see the pattern of weird times when I select "Use Network Location" (with all three location providers), as well as when I set my locations in the "Custom Location". "Custom Time Periods" displays normally.

**Comment by mabawsa** [comment]
I am using the Github version, the location uses network time.

**Comment by mabawsa** [comment]
Not gonna dox myself, so I rounded the value:
35.4, 139.6

**Comment by TobiZog** [comment]
I've found the bug! The next Update (v.2.4) will fix this. Thanks for your help :)

**Comment by mabawsa** [comment]
Thanks, works great now. Wonderful work!

**Comment by Leafback** [comment]
Also confirming the fix, and it's a perfect gradient, too!

For fwiw, I noticed that the bugfix said that it fixed issues with locations near the dateline. My lat long, without doxing, is 45.5, -122.6. Seems to still hold true for what was my issue, too.
