### ISSUE TITLE
Not upgrading wallpaper

### ISSUE THREAD

**Issue by Mark3xtrm** [TobiZog/cinnamon-dynamic-wallpaper#17]
It seems that in one of the very latest versions the background is no longer updated automatically, as the extension is supposed to do.

If I go into the extension's "configure" and click "apply" (after I reselect a wallpaper in "Select an image set" - but I think even without reselecting one) the wallpaper is updated to the one adhering to the current time.

I'm on Mint Cinnamon 21.3.

**Comment by Mark3xtrm** [comment]
So no answer?

**Comment by TobiZog** [comment]
Did you reinstall the whole plugin?

If the error keeps there, please start the config tool from the terminal and post errors here with the bash line:
`python3 ~/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py`

**Comment by Mark3xtrm** [comment]
> Did you reinstall the whole extension?
> 
> If the error keeps there, please start the config tool from the terminal and post errors here with the bash line: `python3 ~/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py`

Yes, I tried reinstalling, just from the Mint extensions window, but nothing.

Then I did a few small tests.

I use pyenv, and I had pyenv global set to a non-"system". So every time, when I ran  (either from home, or from inside src itself), it would give me an error like `ModuleNotFoundError: No module named 'gi'`.
So I did a few things, including installing `python3-gi` and `libgirepository1.0-dev` `gobject-introspection`, but it seemed to bring other problems.

Then, trivially, I changed with pyenv the version from the 3.x version I was using (I tried several, 3.8, 3.12.1) to 3.10.12 (set by choosing "system" on pyenv), and the command no longer gave me any errors.

Is it going to crash something using virtual enviroments, or something like that?

Now I hope it works. That said, I can't change global version of Python with pyenv, I guess. I hope that is not the case.

**Comment by TobiZog** [comment]
Very strange behavior. The extension needs only "heif-convert", which will be request by the user on first start...

`python3-gi` is delivered by Linux Mint itself if you don't removed it.

But all in all it sound like its work now, right?

**Comment by Mark3xtrm** [comment]
> Very strange behavior. The extension needs only "heif-convert", which will be request by the user on first start...
> 
> `python3-gi` is delivered by Linux Mint itself if you don't removed it.
> 
> But all in all it sound like its work now, right?

Yeah, strange.
Now it works, after I set pyenv globlal to "system" again.
Anyway, it seems to be bothering it to change the Python version to pyenv, or something like that, in short.

Thanks for your help, and kudos to you and your nice piece of software
