### ISSUE TITLE
Importing an HEIC image breaks the extension completely 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [TobiZog/cinnamon-dynamic-wallpaper#2]
Extension just stops working completely and the background switches to a random linux mint wallpaper. I have a 4k screen, so I have downloaded a 4k heic wallpaper. First, it broke on a 5k wallpaper, then the 4k. I can close it and open it, but clicking the "image configurater" doesn't do anything anymore. In order for the extension to resume functionality, I'd have uninstall it then reinstall.

**Comment by KarkanAlzwayed** [comment]
> 3\. python3 image-configurator.py

Did that and this is what the terminal said after the whole thing just crashed
```
File contains 3 images
Written to /home/kalzi/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted//plants-1.jpg
Written to /home/kalzi/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted//plants-2.jpg
Written to /home/kalzi/.local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/images/extracted//plants-3.jpg
[kalzi@EOS image-configurator]$ 
```
Here is the image I'm using (I had to zip it since github didn't allow uploading it)

[plants.heic.tar.gz](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/files/12410488/plants.heic.tar.gz)

**Comment by TobiZog** [comment]
Thanks! I think, I got the problem. I will fix it with the next update this week.

**Comment by KarkanAlzwayed** [comment]
You are welcome. Let me know if you need testing.

**Comment by TobiZog** [comment]
With the latest release, the issue should be solved. If it's not, please tell me.
