### ISSUE TITLE
Settings are not available on Extensions page in version 5.4

### ISSUE THREAD

**Issue by cac483** [TobiZog/cinnamon-dynamic-wallpaper#20]
When adding the Cinnamon Dynamic Wallpaper extension through the "Download" Extensions tab, the settings button is grayed out under the "Cinnamon Dymaic Wallpaper" entry under the "Manage" Extensions tab.  The only way to get to the settings is by creating a launcher icon with the following command:

python3 ".local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py"

**Comment by TobiZog** [comment]
Can you describe your system? Which version of Linux Mint do you use? Did you get an error on in Melange (Shortcut Super Key + L, than see in the "Log")?

**Comment by cac483** [comment]
> Can you describe your system? Which version of Linux Mint do you use? Did you get an error on in Melange (Shortcut Super Key + L, than see in the "Log")?

Here is information from neofetch of my system:

OS: Linux Mint 21.3 x86_64 
Host: HP EliteDesk 800 G2 DM 35W 
Kernel: 6.8.0-35-generic 
Uptime: 6 days, 14 hours, 13 mins 
Packages: 3139 (dpkg) 
Shell: bash 5.2.21 
Resolution: 1920x1017 
DE: Cinnamon 6.0.4 
WM: Mutter (Muffin) 
WM Theme: WhiteSur-Dark-solid (Mint-Y) 
Theme: WhiteSur-Dark-solid [GTK2/3] 
Icons: WhiteSur-dark [GTK2/3] 
Terminal: guake 
CPU: Intel i5-6500T (4) @ 3.100GHz 
GPU: Intel HD Graphics 530 
Memory: 3589MiB / 15874MiB 

I reviewed the logs and did not find any error.

Here is a screenshot of what I am seeing on the Extensions window.  The settings button is grayed out.

![2024-06-10 17_21_52-Clipboard](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/163902224/6272d6e9-e0d5-4c30-922f-7d19b81f272a)

**Comment by cac483** [comment]
I just realized that I had not enabled the extension by pressing the + button below.  Once I did that, the settings button works.  Ugh.  :roll_eyes:  Such a simple thing to miss.

Thanks for your attention to this, though.  I appreciate it.
