### ISSUE TITLE
Error message on startup in Manjaro Cinnamon

### ISSUE THREAD

**Issue by jorgenask86** [TobiZog/cinnamon-dynamic-wallpaper#23]
Hi! Thank you for a great wallpaper extension by the way :)

Minor issue:

In Manjaro Cinnamon I get an error message on startup using dynamic wallpapers. I know it is the Dynamic wallpapers "fault" because the error only appears when using dynamic wallpaper and dissapears when using a regular wallpaper.

![error message manjaro cinnamon](https://github.com/user-attachments/assets/c1f3d055-fd48-4a43-a12c-4634d37dba45)

Could this message be caused by manjaro not having apt installed ? as it is based on arch ?
And how could I stop this message from appearing ?

Kind regards from
Jørgen

**Comment by jorgenask86** [comment]
Seems like I don't get the error message if I start the dynamic wallpaper using this command in terminal in my home folder.

python3 .local/share/cinnamon/extensions/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py

**Comment by TobiZog** [comment]
This seems to be an error with apt. I will find a solution for Arch and Fedora based distros.

**Comment by jorgenask86** [comment]
Perfect! Thanks!
