### ISSUE TITLE
Unable to add images

### ISSUE THREAD

**Issue by 13gemini** [TobiZog/cinnamon-dynamic-wallpaper#4]
Hello,
I have been unable to add the additional wallpaper (images) to the Cinnamon Dynamic Wallpaper.  I have downloaded the zip, gone though the commands, added the wallpaper folders to images in 4.8 and 5.4 with no joy.  

Thanks
13gemini 
William

**Comment by TobiZog** [comment]
You've added the wallpapers folder (path?) to `/home/Pictures/`? 

At first, I would recommend the installation through the extension manager. It copies all files to the right locations. If this is not possible, make sure, the folder is here located:

![image](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/67568441/871ffa4e-ec8f-4d34-a632-b265725cf751)

Then, if should appear in the extension manager and have to be activated.

**Comment by 13gemini** [comment]
Thanks so much, I really appreciate your response. That took care of my issue.
