### ISSUE TITLE
Inaccurate Location estimation

### ISSUE THREAD

**Issue by Gibbs-Free-Energy** [TobiZog/cinnamon-dynamic-wallpaper#7]
First off, I love this extension. Secondly, the Longitude estimation using "Estimate coordinates via network" was inverted for me. My longitude is near 95° and the extension was estimating -95°. The Latitude value was correct. It took me a bit to realize why the wallpapers didn't match the time.

**Comment by TobiZog** [comment]
Thanks! I will fix this with Version 2.0, coming this year.

**Comment by TobiZog** [comment]
Can you try the v.2.0 Beta to test the issue again?

**Comment by Gibbs-Free-Energy** [comment]
I tested the v.2.0 Beta and the issue has been resolved. Well done! I also enjoy the new layout since it's easier to see which wallpaper corresponds to which time block. Cheers.

**Comment by TobiZog** [comment]
Nice! Stable release will coming in the next days. Have fun with my work :D
