### ISSUE TITLE
Add localisation support 

### ISSUE THREAD

**Issue by blogdron** [TobiZog/cinnamon-dynamic-wallpaper#8]
Maybe add `pot` file like in other extensions. Community can translate interface to different languages :)

**Comment by TobiZog** [comment]
Do you have a good reference to implement translation support? I've tried it on multiple ways, but no works.

**Comment by blogdron** [comment]
> Do you have a good reference to implement translation support? I've tried it on multiple ways, but no works.

I don`t known :)

**Comment by TobiZog** [comment]
I've contacted the Linux Mint team to upgrade the translation script. Now it works. With the next release, the extension will support localization support. In the first release, I will offer English, German and Dutch.

Do you want to contribute another language? ;)

**Comment by blogdron** [comment]
>Now it works.

Cool, thanks. Yep, I add Russian language as soon as everything is ready. Another person wanted to translate into Kazakh.

**Comment by blogdron** [comment]
Strange... 😧

My Steps:
 * fork and clone https://github.com/linuxmint/cinnamon-spices-extensions
 * create branch `cinnamon-dynamic-wallpaper@TobiZog`
 * add `ru.po` file and [translate](https://gist.github.com/blogdron/c16057db10c12ac996bd587fad87c58c) (not final)
* do test 
 ```sh
./cinnamon-spices-makepot cinnamon-dynamic-wallpaper@TobiZog --install
```
* restart Cinnamon

Now i see new translated text in Cinnamon Settings extension description

![img](https://i.ibb.co/Tk3Q9Yz/2024-02-09-14-12-06.png)

But extension not translated 🤔 
![img](https://i.ibb.co/8chWnY4/2024-02-09-14-15-36.png)

```sh
cinnamon --version
Cinnamon 5.8.4
```

I translated many extensions this way. And everything worked. Currently the translation only applies to the Cinnamon settings window. Maybe I'm missing something. But for now I won’t make a pull request with translation.

Sudo cast @haggen88. Hello @haggen88! I saw that you recently did a Spanish translation for this extension. 
 *  https://github.com/linuxmint/cinnamon-spices-extensions/pull/563

I would like to ask you used `./cinnamon-spices-makepot cinnamon-dynamic-wallpaper@TobiZog --install`  for test? And you view you translated result in extension window? 

I will be grateful for your answer. So I can understand the problem I have and am I doing something wrong or the new translations really are not applied to the extension 😊

**Comment by blogdron** [comment]
Or was I just in a hurry? And do you need to wait for the update of the extension itself? 🙃

**Comment by haggen88** [comment]
I did not use such a tool for testing. I just translated the [pot](https://github.com/linuxmint/cinnamon-spices-extensions/blob/master/cinnamon-dynamic-wallpaper%40TobiZog/files/cinnamon-dynamic-wallpaper%40TobiZog/po/cinnamon-dynamic-wallpaper%40TobiZog.pot) file to po.es with poedit.   To test the languages, I move the .mo file to .local/share/locale/es/LC_MESSAGES

btw...  I don't know if it's related to this problem, but what I noticed is that the github verification didn't allow to approve the po files, last I remember @rcalixte was fixing the makepot script.

**Comment by rcalixte** [comment]
> [TobiZog](https://github.com/TobiZog) I did not use such a tool for testing. I just translated the [pot](https://github.com/linuxmint/cinnamon-spices-extensions/blob/master/cinnamon-dynamic-wallpaper%40TobiZog/files/cinnamon-dynamic-wallpaper%40TobiZog/po/cinnamon-dynamic-wallpaper%40TobiZog.pot) file to po.es with poedit. To test the languages, I move the .mo file to .local/share/locale/es/LC_MESSAGES

This is what the script does for you, the only difference is that it will install all of the languages that exist (the same as when you install it).

> btw... I don't know if it's related to this problem, but what I noticed is that the github verification didn't allow to approve the po files, last I remember @rcalixte was fixing the makepot script.

I think this might be a problem elsewhere if it's still happening. The scripts on all the repositories for the Spices should be stable as long as you are on the latest version.

**Comment by rcalixte** [comment]
@blogdron Is that second screenshot from after you finished translating and the translation was installed? I ask because that's the Glade UI, not the regular Cinnamon one. @TobiZog It might be missing a piece there if it's not pulling the strings properly. I can take a look in a little bit but I suspect if there's an issue that it's related to something with gettext and the Glade UI.

**Comment by TobiZog** [comment]
I will work on it in the next couple days. So, please wait, until I've created a complete pot file with all strings from the glade file, Python script and the JavaScript part ;)

**Comment by rcalixte** [comment]
> I will work on it in the next couple days. So, please wait, until I've created a complete pot file with all strings from the glade file, Python script and the JavaScript part ;)

You can just run `./cinnamon-spices-makepot cinnamon-dynamic-wallpaper@TobiZog` and it will do all of that for you. It will pull in whatever is in the local repository at the time it is run. It will also update all of the existing translations to update the strings as well.

**Comment by blogdron** [comment]
@rcalixte  yes add po file -> translate po file -> run install script, restart cinnamon (just in case) and open extension window settings. I described my steps step by step above. I try not to introduce any special actions into the translation process to avoid problems. 

You probably just need to try to reproduce everything on your machine (preferably let several people do this on different systems) and if it turns out that everyone doesn’t use the new translation, then the problem is somewhere in the scripts, and if it works for some and not for others , which means there are some system features and differences in versions or something else. It seems to me that there is no need to worry and rush. You just need to take this extension, add a translation file (into any of your languages) and just check whether the translation is applied. And based on these statistics, think further.

PS Other extensions are translated well, the translation is partially applied to the selection window (turning on and off) the extension.

These are just thoughts out loud.

```sh
dron@gnu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie
dron@gnu:~$ cinnamon --version
Cinnamon 5.8.4
dron@gnu:~$
```
Extension installed from spices.

**Comment by blogdron** [comment]
@haggen88 thanks for answer 
@rcalixte thanks for help

**Comment by TobiZog** [comment]
With version 2.3 language support is included. You can now add more languages :)

A little tutorial is in my Readme included.

**Comment by rcalixte** [comment]
@TobiZog Is there a way to support localization for these items without impacting the functionality? The rest looks fantastic! I'm glad this worked out.

![2024-02-15_13-30-00](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/10281587/a514d41f-8c16-4e3c-8217-0e831ca9bfb3)
![2024-02-15_13-30-27](https://github.com/TobiZog/cinnamon-dynamic-wallpaper/assets/10281587/40f2dc23-f471-44f3-8783-842098b1ab4e)

**Comment by TobiZog** [comment]
@rcalixte I will work on it
